### ISSUE TITLE
MS3PRO 

### ISSUE THREAD

**Issue by Ms3pro** [hankedan000/EThrottle#29]
Hi! Does it work on ms3pro? Can you make a video instruction on how to connect this to a megasquirt and set up a can for communication?

I uploaded this code to arduino mega + mcp2515 and turned on ms3 pro added ini Can1 for end-to-end transmission, but I get the error there is no connection with Can1 and ms3pro remains to work alone.

**Comment by hankedan000** [comment]
This code is not designed to run on an Arduino Mega (atmega2560). The code is intended to run on a regular Arduino UNO or anything with the atmega328 chip.

That being said, I don't see why the CAN passthrough functionality wouldn't work with an ms3pro because the 29bit CAN protocol is the same as the ms2.

I haven't actually got this installed in my car yet, but when I do, I might write up a setup guide or make a quick video.

**Comment by Ms3pro** [comment]
![IMG_20230517_201435](https://github.com/hankedan000/EThrottle/assets/133560006/6eb86245-3985-4480-bee9-1e84b2f02c12)
![IMG_20230517_201413](https://github.com/hankedan000/EThrottle/assets/133560006/a99c6c8a-698c-435e-aa30-0a854c58f50c)

**Comment by hankedan000** [comment]
If you go to File > Project Properties, and then the "CAN Devices" tab.
Do you see the EThrottle device get detected under one of the devices like this?
![image](https://github.com/hankedan000/EThrottle/assets/216870/5ed89369-3ee8-4229-99bc-c7938b1a0e67)
I have my CAN ID flash with a 5, so it's showing up as device 5 in the list.
https://github.com/hankedan000/EThrottle/blob/main/src/avr/EThrottle/can.h#L8

If it's not showing up, then something must be wrong with the CAN communication. If it does show up, then maybe you just have the device setup with the wrong CAN ID (the dialog does say "A device is responding, but not at the project assigned CAN ID.")

**Comment by Ms3pro** [comment]
![IMG_20230518_191102](https://github.com/hankedan000/EThrottle/assets/133560006/ac4d50b3-0ecb-4efb-bc94-5bbef00cbf61)
![IMG_20230518_191207](https://github.com/hankedan000/EThrottle/assets/133560006/53e199be-43d7-438d-b6ed-9c89157052ba)
![IMG_20230518_191551](https://github.com/hankedan000/EThrottle/assets/133560006/affa1720-43da-4e7a-b6f7-19d18ebff32b)
![IMG_20230518_191606](https://github.com/hankedan000/EThrottle/assets/133560006/dd67e1b6-469b-490f-8e51-5981879a8cda)
![IMG_20230518_191726](https://github.com/hankedan000/EThrottle/assets/133560006/4645c9fd-f114-4eaa-8daa-1bde548cf6ac)
![IMG_20230518_193619](https://github.com/hankedan000/EThrottle/assets/133560006/6cbe520b-7b9d-4e13-8bbd-d378b60e54f9)
![IMG_20230518_193646](https://github.com/hankedan000/EThrottle/assets/133560006/947b49a7-ea65-40fe-bbfe-807afd69e7f4)
![IMG_20230518_193709](https://github.com/hankedan000/EThrottle/assets/133560006/a6419786-0209-4821-9378-3f07d078b9b0)
![IMG_20230518_193816](https://github.com/hankedan000/EThrottle/assets/133560006/13ce1f17-5b91-41c1-8a3e-18ce4b97feab)
![IMG_20230518_194105](https://github.com/hankedan000/EThrottle/assets/133560006/7d97da31-ca87-4100-a823-5828bab66417)
![IMG_20230518_194145](https://github.com/hankedan000/EThrottle/assets/133560006/0bf98fb2-2021-4fb1-8f6d-94c6e514e85b)
![IMG_20230518_194156](https://github.com/hankedan000/EThrottle/assets/133560006/988fc689-24f9-4c9d-b8c1-bf6952ef66ac)
![IMG_20230518_194206](https://github.com/hankedan000/EThrottle/assets/133560006/41429ef0-6f9d-4421-a084-17b556eb89d0)
![IMG_20230518_194216](https://github.com/hankedan000/EThrottle/assets/133560006/b7af712e-759e-4942-a233-8ea57f5b44f6)
![IMG_20230518_194224](https://github.com/hankedan000/EThrottle/assets/133560006/35303aa5-220d-43e3-8aa3-e879400ad69e)
![IMG_20230518_194234](https://github.com/hankedan000/EThrottle/assets/133560006/214779c0-c841-4583-bc4e-21e89837bfaa)
![IMG_20230518_194255](https://github.com/hankedan000/EThrottle/assets/133560006/45770b17-5be3-48d6-ad77-c9e0f4b4c317)
![IMG_20230518_194307](https://github.com/hankedan000/EThrottle/assets/133560006/393fc7e9-5ff8-4f10-a8b4-20fa7e3f8f2e)
![IMG_20230518_194341](https://github.com/hankedan000/EThrottle/assets/133560006/0c9eb07c-c198-4768-bf17-fd0a4586d70d)
![IMG_20230518_194349](https://github.com/hankedan000/EThrottle/assets/133560006/c4bb93b7-0953-42a1-b4d0-76e54b0074df)
![IMG_20230518_194359](https://github.com/hankedan000/EThrottle/assets/133560006/6f041bb8-152d-4c88-8940-608b41fa0653)
![IMG_20230518_194852](https://github.com/hankedan000/EThrottle/assets/133560006/ec919e7b-db89-4bad-a32d-b11c5581d863)
![IMG_20230518_194917](https://github.com/hankedan000/EThrottle/assets/133560006/4f631f68-f6f8-4a68-89c8-ea97dde0ba81)
Mcp2515 16mhz CAN speed 500

**Comment by hankedan000** [comment]
Hmmmm you mention your MCP2515 has a 16MHz oscillator?
Most MCP2515 units I've bought off Ebay have a 8MHz oscillator. If you're is really 16MHz, then you'll need to change this constant to `MCP_16MHZ`: https://github.com/hankedan000/MegaCAN/blob/main/src/MegaCAN_Device.cpp#L99

**Comment by Ms3pro** [comment]
Yes , 16mhz and I soldered this crystal myself and everything works fine on other projects with 16mhz . I 'll try to change it in the code . I removed the jumper with a knife because I was looking for a reason, now I will return the jumper to its place. I'll try again and write the results.

**Comment by Ms3pro** [comment]
![Uploading IMG_20230518_230531.jpg…]()
👍

**Comment by Ms3pro** [comment]
Now I see the green CAN tx indicator, but the blue id5 is not lit. I don't understand how to configure the offset and ID of the tables. Perhaps I am incorrectly specifying the offset and id in the settings.

**Comment by Ms3pro** [comment]
![ms](https://github.com/hankedan000/EThrottle/assets/133560006/f91809c2-d3b5-4fb0-b75d-abef37898621)
![Screenshot_2023-05-18-23-53-26-488_com miui gallery](https://github.com/hankedan000/EThrottle/assets/133560006/c5c17332-8dfc-470a-9017-dd747f768758)
![IMG_20230518_231947](https://github.com/hankedan000/EThrottle/assets/133560006/5a156aae-97d3-4fae-9864-808a476eb32f)

**Comment by Ms3pro** [comment]
https://github.com/crycode-de/mcp-can-boot 
Does it need to be loaded into the arduino processor along with the throttle design?

**Comment by hankedan000** [comment]
You do not need the mcp-can-boot bootloader. Although it is nice for being able to remotely flash new firmware over the CAN bus.

You do not need to enable any of the Megasquirt broadcast features that you're screenshoting for Tuner Studio to detect the CAN device.

If your CAN bus is wired correctly, and the device is functioning correctly, it should get detected and displayed in the project drop down.

At this point, you might want to put some INFO() logs in here and see if the EThrottle device is getting any CAN interrupts from messages off the bus.
![image](https://github.com/hankedan000/EThrottle/assets/216870/560c9a40-5756-43b0-83dc-6aec732353ab)

I really think you might be hitting issues with trying to run this firmware on a chip that it wasn't intended for. I'm doing some interest stuff with timing the ADC measurements relative to the motor driver PWM signals. The code could be getting stuck in an ISR or something weird because it wasn't intended for an Atmega2560.

If you just want to try getting the CAN bus stuff working, I'd recommend commenting out the throttle related code and just let the CAN interrupts get serviced and the canLoop() called in the main loop.
![image](https://github.com/hankedan000/EThrottle/assets/216870/36fc4135-28b1-4465-a782-0dfc98a2ce5e)

Alternatively, if you're not interested in the EThrottle code itself, I have a much simpler GPIO CAN module example project in my MegaCAN repo (https://github.com/hankedan000/MegaCAN/tree/main/examples/GPIO). Hopefully that should run okay without having to worry the Atmega328 specific code I've developed for this project.

**Comment by Ms3pro** [comment]
It turned out to connect mega 2560 GIPIO +MS3PO! Now everything works and ADC shows in the tuner studio.

**Comment by Ms3pro** [comment]
![Uploading IMG_20230521_125525.jpg…]()

**Comment by hankedan000** [comment]
Awesome! Glad it works out. So it was just a wiring issue the whole time?
Did you have to comment out any of the throttle code like I was suggesting?

**Comment by Ms3pro** [comment]
There were problems with the 16mhz crystal, I fixed it in the code from 8mhz to 16mhz and everything works. I don't understand how to configure tables and offsets in the settings window now, I have 6 egts and it was good if ms controlled them. Now I 'll try DBW as you said .

**Comment by Ms3pro** [comment]
![IMG_20230521_201226](https://github.com/hankedan000/EThrottle/assets/133560006/7ad1a4c6-0df0-430d-8166-a93c9a2a6ceb)
The throttle code does not work, I tried to comment out these lines, but it is still undetected in the device list.

**Comment by hankedan000** [comment]
Hey man. I don't know what to tell you. The code is pretty robust on my setup, but there must be something different about yours. I recommend adding debug prints in the code to see where it might be getting stuck, or just not responding. You can pretty easily add a log in the CAN ISR and see if it's receiving any of those requests you have printed. If it is getting them, them follow the code and see why it's not responding to them.

The repo is not road tested at all, so I can't make any promises for how well it works yet.

**Comment by hankedan000** [comment]
i've had others report that this code can communicate with an MS3 device via can pass through. closing the issue.

**Comment by Ms3pro** [comment]
Hi, your project is cool! I bought a arduino nano now everything works fine👍👏
